# Generated by Django 5.2.14 on 2026-05-16 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Product Name')),
                ('category', models.CharField(choices=[('school', 'School Stationery'), ('office', 'Office Stationery')], default='school', max_length=10)),
                ('image', models.ImageField(help_text='Upload high-quality product photo', upload_to='products/')),
                ('short_description', models.CharField(help_text='Displayed directly in the gallery grid', max_length=255)),
                ('detailed_description', models.TextField(help_text='Displayed inside the popup modal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
